[project]
authors = [{name = "Johannes Tenhumberg", email = "johannes.tenhumberg@gmail.com"}]
name = "wzk"
requires-python = "== 3.13"
version = "0.1.0"
dependencies = ["msgpack>=1.1.2,<2", "ortools>=9.14.6206,<10"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
wzk = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.3.5,<3"
pixi-pycharm = ">=0.0.10,<0.0.11"
scipy = ">=1.16.3,<2"
hatchling = ">=1.27.0,<2"
matplotlib = ">=3.10.8,<4"
scikit-image = ">=0.25.2,<0.26"
joblib = ">=1.5.2,<2"
fire = ">=0.7.1,<0.8"
scikit-learn = ">=1.7.2,<2"
typing = ">=3.10.0.0,<4"
einops = ">=0.8.1,<0.9"
plotly = ">=6.5.0,<7"
